---
- name: Install Apache HTTP Server
  hosts: web
  become: true
  tasks:
    - name: Install Apache HTTP Server
      apt:
        name: apache2 # Package name for Apache HTTP Server
        state: present
